import { ImageItem } from '../../image-catalog/models/image-item';
import { ImageFormat } from '../../shared/enums/image-format.enum';
import { MockImageItem } from '../../image-catalog/models/mock-image-item';


export const IMAGES: ImageItem[] = [
  new MockImageItem(1, ImageFormat.webp),
  new MockImageItem(2, ImageFormat.jpg),
  new MockImageItem(3, ImageFormat.webp),
  new MockImageItem(4, ImageFormat.jpg),
  new MockImageItem(5, ImageFormat.webp),
  new MockImageItem(6, ImageFormat.jpg),
  new MockImageItem(7, ImageFormat.webp),
  new MockImageItem(8, ImageFormat.jpg),
  new MockImageItem(9, ImageFormat.webp),
  new MockImageItem(10, ImageFormat.jpg),
  new MockImageItem(11, ImageFormat.webp),
  new MockImageItem(12, ImageFormat.jpg),
  new MockImageItem(13, ImageFormat.webp),
  new MockImageItem(14, ImageFormat.jpg),
  new MockImageItem(15, ImageFormat.webp),
  new MockImageItem(16, ImageFormat.jpg),
  new MockImageItem(17, ImageFormat.webp),
  new MockImageItem(18, ImageFormat.jpg),
  new MockImageItem(19, ImageFormat.webp),
  new MockImageItem(20, ImageFormat.jpg),
  new MockImageItem(21, ImageFormat.webp),
  new MockImageItem(22, ImageFormat.jpg),
  new MockImageItem(23, ImageFormat.webp),
  new MockImageItem(24, ImageFormat.jpg),
  new MockImageItem(25, ImageFormat.webp),
  new MockImageItem(26, ImageFormat.jpg),
  new MockImageItem(27, ImageFormat.webp),
  new MockImageItem(28, ImageFormat.jpg),
  new MockImageItem(29, ImageFormat.webp),
  new MockImageItem(30, ImageFormat.jpg),
  new MockImageItem(31, ImageFormat.webp),
  new MockImageItem(32, ImageFormat.jpg),
  new MockImageItem(33, ImageFormat.webp),
  new MockImageItem(34, ImageFormat.jpg),
  new MockImageItem(35, ImageFormat.webp),
  new MockImageItem(36, ImageFormat.jpg),
  new MockImageItem(37, ImageFormat.webp),
  new MockImageItem(38, ImageFormat.jpg),
  new MockImageItem(39, ImageFormat.webp),
  new MockImageItem(40, ImageFormat.jpg),
  new MockImageItem(41, ImageFormat.webp),
  new MockImageItem(42, ImageFormat.jpg),
  new MockImageItem(43, ImageFormat.webp),
  new MockImageItem(44, ImageFormat.jpg),
  new MockImageItem(45, ImageFormat.webp),
  new MockImageItem(46, ImageFormat.jpg),
  new MockImageItem(47, ImageFormat.webp),
  new MockImageItem(48, ImageFormat.jpg),
  new MockImageItem(49, ImageFormat.webp),
  new MockImageItem(50, ImageFormat.jpg),
];
